-- Create store_settings table
CREATE TABLE IF NOT EXISTS public.store_settings (
    id bigint generated by default as identity primary key,
    bakery_name text not null default 'The Home Bake',
    whatsapp_number text not null default '',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
ALTER TABLE public.store_settings ENABLE ROW LEVEL SECURITY;

-- Policy: Public can read settings
CREATE POLICY "Public can view store settings" 
ON public.store_settings FOR SELECT 
TO public 
USING (true);

-- Policy: Authenticated users (Admin) can update settings
CREATE POLICY "Admin can update store settings" 
ON public.store_settings FOR UPDATE 
TO authenticated 
USING (true)
WITH CHECK (true);

-- Policy: Authenticated users can insert (for initial setup)
CREATE POLICY "Admin can insert store settings" 
ON public.store_settings FOR INSERT 
TO authenticated 
WITH CHECK (true);

-- Seed initial data if table is empty
INSERT INTO public.store_settings (bakery_name, whatsapp_number)
SELECT 'The Home Bake', '60123456789'
WHERE NOT EXISTS (SELECT 1 FROM public.store_settings);

-- Ensure products table policies (assuming table exists)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Policy: Public can view products
DROP POLICY IF EXISTS "Public can view products" ON public.products;
CREATE POLICY "Public can view products" 
ON public.products FOR SELECT 
TO public 
USING (true);

-- Policy: Admin can manage products (Insert, Update, Delete)
DROP POLICY IF EXISTS "Admin can insert products" ON public.products;
CREATE POLICY "Admin can insert products" 
ON public.products FOR INSERT 
TO authenticated 
WITH CHECK (true);

DROP POLICY IF EXISTS "Admin can update products" ON public.products;
CREATE POLICY "Admin can update products" 
ON public.products FOR UPDATE 
TO authenticated 
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "Admin can delete products" ON public.products;
CREATE POLICY "Admin can delete products" 
ON public.products FOR DELETE 
TO authenticated 
USING (true);
